/hri_face_detect:
  remappings:
    image: /camera1/image_raw
    camera_info: /camera1/camera_info

/robot_face/expressive_eyes:
  ros__parameters:
    general:
      headless: true
  remappings:
    /robot_face/look_at: /look_at

